<h1>Introduction to Numpy</h1><p><img src="images/1line.png" width="100%" /></p>
<ul>
<li>NumPy is a Python module designed for scientific computation.</li>
<li id="33df" class="graf graf--p graf-after--figure">It enables us to do computation more efficiently and effectively than with Python alone.</li>
<li>This is why it is one of the libraries commonly used for big data analytics.</li>
</ul>
<h3>NumPy Characteristics</h3>
<ul>
<li>NumPy arrays are n-dimensional array objects and they are a core component of scientific and numerical computation&nbsp;in Python.</li>
<li>NumPy provides tools for integrating your code with existing C,&nbsp;C++, and Fortran code.</li>
<li>NumPy also provides many useful tools to help&nbsp;you perform linear algebra, generate random numbers, and much, much more.</li>
</ul>
<h3>NumPy Arrays</h3>
<ul>
<li>NumPy arrays are an additional data type provided by NumPy,&nbsp;and they are used for representing vectors (one dimensional arrays) and matrices (two dimensional arrays).</li>
<li>Unlike dynamically growing Python lists, NumPy arrays&nbsp;have a size that is fixed when they are constructed.</li>
<li>Elements of NumPy arrays are also all of the same data type leading to more efficient and simpler code than using Python's standard data types.</li>
<li>By default, the elements are floating point numbers.</li>
</ul>
<h3>Using NumPy</h3>
<ul>
<li>Begin by importing NumPy into Python:</li>
</ul>





In [10]:
# import numpy
import numpy as np

<ul>
<li>This is the import typically used for NumPy.</li>
<li>NumPy has three methods that can be used to create and auto-populate arrays
<ul>
<li><strong>np.zeros()</strong>: Creates an array initialized with 0.</li>
<li><strong>np.ones()</strong>: Creates an array initialized with 1.</li>
<li><strong>np.empty()</strong>: Allocates the requested space for the array, but does not initialize it,&nbsp;meaning that the content could be anything, whatever&nbsp;happens to be in the computer's memory at the location where&nbsp;the array is set up.</li>
<li>If you are dealing with a very large array&nbsp;and you know for sure that you will be updating each element of the array, this could save you some computation time<br />because Python doesn't need to initialize the array.</li>
</ul>
</li>
<li>These methods can be used to create one dimensional vectors, two dimensional&nbsp; matrices and beyond.</li>
<li>When defining a 2-dimensional matrix a tuple is used:
<ul>
<li>The first argument is the number of rows in the table</li>
<li>The second argument is the number of columns in our table.</li>
</ul>
</li>
</ul>


In [9]:
import numpy as np
zeros_vector = np.zeros(5)
zeros_matrix = np.zeros((5,3))

print(zeros_vector)
print(zeros_matrix)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


<h3 id="2391" class="graf graf--p graf-after--p">Using One-dimensional NumPy Arrays</h3>
<ul>
<li>We can also construct NumPy arrays using specified values, in which case, we use the <strong>np.array()</strong> function, and the input argument to the function is a sequence of numbers, typically a list of numbers.</li>
</ul>



In [7]:
# python list
a = [1,2,3,4,5,6,7,8,9]

# numpy array
b = np.array([1,2,3,4,5,6,7,8,9])

<ul><li>If you were to print them, you wouldn&rsquo;t see much difference.</li></ul>

In [8]:
print(a)
print(b)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]


<li>However,<span>&nbsp;</span><span class="markup--quote markup--p-quote is-other" data-creator-ids="anon">np arrays provide faster computation and easier manipulation.</span></li>
</ul>
<h3 >Using Two-dimensional NumPy Arrays</h3>
<ul>
<li>By convention lower case variables are used for vectors or one-dimensional arrays and upper case variables are used for&nbsp;matrices, or two-dimensional arrays.</li>
<li>When you construct a two-dimensional NumPy array, you specify the elements of each row as a list&nbsp;and you can then define the entire table as a list that contains at its elements each of the lists of the row elements you've defined.</li>
</ul>
<pre style="font-size: 2em; font-weight: bold;">
A=[[<span style="color:red">11,12,13</span>],
   [<span style="color:cyan">21,22,23</span>],
   [<span style="color:purple">31,32,33</span>]]
</pre>
<ul>
<li>Let's define the first row as consisting of numbers 11, 12 and 13.</li>
<li>The second row consists of the numbers 21, 22, and 23.</li>
<li>Finally, the third row contains 31, 32 and 33.</li>
<li>They are defined in three lists that are separated by a comma.</li>
<li>And we will embed these three lists inside yet another list, to create a&nbsp;nested list object.</li>
</ul>



In [3]:
import numpy as np
A=np.array([[11,12,13],[21,22,23],[31,32,33]])
display(A)

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

<ul>
<li>Finally, sometimes you want to turn the table sideways.</li>
<li>This is called taking the transpose of a matrix, which&nbsp;means that the first row becomes the first column,&nbsp;the second row becomes the second column, and so on.</li>
<li>We can transpose a two-dimensional array using the transpose method.</li>
</ul>

In [6]:
# Transposed Array
display(A.transpose())

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

<hr />
<h3>Reference</h3>
<p>Jukka-Pekka Onnela, Python for Research, Python Libraries and Concepts Used in Research, CC 2.2.1 Introduction to NumPy, edX, <a href="https://www.edx.org/course/using-python-for-research" target="_blank" rel="noopener">https://www.edx.org/course/using-python-for-research</a>&nbsp;</p>