<h1>Building and Examinong Numpy Arrays</h1><p><img src="images/1line.png" width="100%" /></p>
<ul>
<li>NumPy provides a couple of ways to construct arrays with fixed, start, and end values, such that the other elements are uniformly spaced between them.</li>
</ul>
<h3>numpy.arange()</h3>
<ul>
<li>Return evenly spaced values within a given interval.</li>
<li>Values are generated within the half-open interval<span>&nbsp;</span><code>[start, stop)</code><span>&nbsp;</span>(in other words, the interval including<span>&nbsp;</span><code>start</code><span>&nbsp;</span>but excluding<span>&nbsp;</span><code>stop</code>).</li>
<li>For integer arguments the function is equivalent to the Python built-in<span>&nbsp;</span><a class="reference external" href="https://docs.python.org/3/library/functions.html">range</a><span>&nbsp;</span>function, but returns an ndarray rather than a list.</li>
</ul>
<code>np.arange([start, ]stop, [step, ]dtype=None)</code>

In [1]:
import numpy as np
np.arange(3)

array([0, 1, 2])

In [2]:
np.arange(3.0)

array([0., 1., 2.])

In [3]:
np.arange(3,7)

array([3, 4, 5, 6])

In [5]:
np.arange(3,7,2)

array([3, 5])

<ul>
<li>When using a non-integer step, such as 0.1, the results will often not be consistent. It is better to use<span>&nbsp;</span><code>linspace</code><span>&nbsp;</span>for these cases.</li>
</ul>
<h3>numpy.linspace()</h3>
<ul>
<li>Return evenly spaced numbers over a specified interval.</li>
<li>Returns&nbsp;<code>num</code>&nbsp;evenly spaced samples, calculated over the interval [<code>start</code>,&nbsp;<code>stop</code>].</li>
<li>The endpoint of the interval can optionally be excluded.</li>
</ul>
<dl class="function">
<dt id="numpy.linspace"><code>np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)</code></dt>
</dl>
<ul>
<li>To construct an array of 5 linearly spaced elements starting with 20 and ending with 30, we can use the NumPy linspace function.</li>
</ul>


In [6]:
np.linspace(20, 30, num=5)

array([20. , 22.5, 25. , 27.5, 30. ])

In [7]:
np.linspace(20, 30, 5) 

array([20. , 22.5, 25. , 27.5, 30. ])

In [8]:
np.linspace(20, 30, num=5, endpoint=False)

array([20., 22., 24., 26., 28.])

<h3>nupmy.shape and numpy.size</h3>
<ul>
<li>Often we need to know the shape of an array or the number of elements in an array.</li>
<li>You can check the shape of an array using shape.</li>
<li>You can check the number of elements of an array with size.</li>
</ul>


In [9]:
X = np.array([[1, 2, 3],
              [4, 5, 6]])
display(X.shape)
display(X.size)

(2, 3)

6

<ul>
<li>Notice that you don't have parentheses following the shape or size in the above examples.</li>
<li>This is because shape and size are data attributes, not methods of the arrays.</li>
</ul>
<h3>numpy.any() &amp; numpy.all()</h3>
<ul>
<li>Sometimes we need to examine whether any elements of an array fulfill some logical condition.</li>
</ul>
<p><code>numpy.any(a, axis=None, out=None, keepdims=False)</code></p>
<ul>
<li>Test whether <strong>any</strong> array element along a given axis evaluates to True.</li>
</ul>
<p><code>numpy.all(a, axis=None, out=None, keepdims=False)</code><span>&nbsp;</span><a class="reference external" href="http://github.com/numpy/numpy/blob/v1.11.0/numpy/core/fromnumeric.py#L1973-L2044"><span class="viewcode-link">[source]</span></a></p>
<ul>
<li>Test whether all array elements along a given axis evaluate to True.</li>
<li>Both methods return single boolean</li>
</ul>

In [10]:
x = np.random.random(10)
x

array([0.77466497, 0.81171748, 0.21329501, 0.98592691, 0.37173804,
       0.6213692 , 0.74602465, 0.01817896, 0.63345021, 0.90112139])

In [11]:
np.any(x>0.9)

True

In [12]:
np.all(x>0.1)

False


<ul>
<li>We generated a one d array using a random number generator.</li>
<li>First, we check if any of the entries are greater than 0.9,</li>
<li>Second, we check if if all of the entries are greater than or equal to 0.1.</li>
<li>To make sense of these results, we can print out the content of x.</li>
<li>Note that the output is either True or False for the whole array.</li>
</ul>

<hr><h3>Reference</h3>

<p >Jukka-Pekka Onnela, Python for Research, Python Libraries and Concepts Used in Research, CC 2.2.4_ Building and Examining NumPy Array, edX,<span>&nbsp;</span><a class="external" style="color: var(--ic-link-color); text-decoration: underline;" href="https://www.edx.org/course/using-python-for-research" target="_blank" rel="noopener"><span>https://www.edx.org/course/using-python-for-research</span></a></p>