<h1>Slicing NumPy Arrays</h1>
<p><img src="images/1line.png" width="100%" /></p>
<ul>
<li>It's easy to index and slice NumPy arrays, whether they are vectors or matrices.</li>
<li>With one-dimension arrays, we can index a given element by its position, keeping in mind that indices start at 0.</li>
<li>With two-dimensional arrays, the first index specifies the row of the array and the second index&nbsp;specifies the column of the array.</li>
<li>This is exactly the way we would index elements of a matrix in linear algebra.</li>
<li><a class="instructure_file_link" title="numpy1.ipynb" href="https://ucdenver.instructure.com/courses/518274/files/19358374/download?wrap=1" data-api-endpoint="https://ucdenver.instructure.com/api/v1/courses/518274/files/19358374" data-api-returntype="File">numpy1.ipynb</a></li>
</ul>
<h3>one-dimensional NumPy Arrays</h3>
<ul>
<li>We import numpy then convert two list to numpy arrays:</li>
<li>To&nbsp;access a single element of the array you just use the index: x[2] gives the element at index 1&nbsp;of v.</li>
</ul>

In [2]:
# One-dimmensional numpy array
import numpy as np 

x=np.array([1, 0, -1])
y=np.array([0, 1, 2])

print(x[2])

-1


<ul>
<li>You can also do slicing to extract part of the array.<br />You specify the start index and the end index, (remembering that you get the element at the start index, but you stop just before the element at the end index).</li>
<li>slicing from 0:2 for both x and y produces the arrays below:</li>
</ul>

In [3]:
# slicing
u = x[0:2]
display(u)

v = y[0:2]
display(v)

array([1, 0])

array([0, 1])

<ul>
<li>The numpy array has many useful properties for example<span style="font-size: 1rem;">&nbsp;</span><a style="font-size: 1rem;" href="https://en.wikipedia.org/wiki/Euclidean_vector">vector</a><span style="font-size: 1rem;">&nbsp;</span><span style="font-size: 1rem;">addition, we can add the two arrays as follows:</span></li>
</ul>

In [4]:
# adding numpy arrays
z=u+v
display(z)

array([1, 1])

<ul>
<li>Where the term &ldquo;z:array([1,1])&rdquo; means the variable z contains an array.</li>
<li>The actual vector operation is shown in figure 2, where each component&nbsp;of the vector has a different color.</li>
</ul>
<p><img style="display: block; margin-left: auto; margin-right: auto;" src="images/u plus v.png" alt="z = u = v" width="381" height="226" /></p>
<ul>
<li>Numpy arrays also follow similar conventions for vector scalar multiplication, for example, if you multiply a numpy array by an integer or float:</li>
</ul>

In [11]:
# multiplying numpy array
y=np.array([1,2])
y=2*y
y

array([2, 4])

<p><img class="alignnone wp-image-5327" style="display: block; margin-left: auto; margin-right: auto;" src="images/2y.png" alt="y=2*z" width="349" height="227"  /></p>
<ul>
<li>Many of the operations of numpy arrays are different from vectors, for example in numpy multiplication does not correspond to dot product or matrix multiplication but element-wise multiplication, we can multiply two numpy arrays as follows:</li>
</ul>

In [12]:
#multiplying 2 arrays
u=np.array([1,2])
v=np.array([3,2])

z=u*v
z

array([3, 4])

<h3><img style="display: block; margin-left: auto; margin-right: auto;" src="images/VectorMultiplication.png" alt="u * v = [3 6]" /></h3>
<h3>Multi-dimensional NumPy Arrays</h3>
<ul>
<li>NumPy arrays can have more dimensions than one of two.</li>
<li>For example, you could have three or four dimensional arrays.</li>
<li>With multi-dimensional arrays, you can use the colon character in place of a fixed value for an index, which means that the array elements corresponding to all values of that particular index will be returned.</li>
<li>For a two-dimensional array, using just one index returns the given row which is consistent with the construction of 2D arrays as lists of lists, where the inner lists correspond<br />to the rows of the array.</li>
</ul>

In [6]:
X = np.array([[1, 0, -1], [0, 1, 2]]) 
Y = np.array([[2, 1, 0], [1, 2, 3]])

# Second column of X and Y
display(X[:, 1])   # array([0,1])
display(Y[:, 1])   # array([1, 2])

# Second row of X and Y
display(X[1, :])   # array([0, 1, 2])

display(Y[1, :])   # array([1, 2, 3])

# Second row of X and Y (shorthand)
display(X[1])      # array([0, 1, 2])

display(Y[1])      # array([1, 2, 3])

array([0, 1])

array([1, 2])

array([0, 1, 2])

array([1, 2, 3])

array([0, 1, 2])

array([1, 2, 3])

<ul>
<li><span>The 2-D arrays share similar properties to&nbsp;</span><a href="https://en.wikipedia.org/wiki/Matrix_(mathematics)">matrices<span>&nbsp;</span></a><span>like scalar multiplication and addition.&nbsp; For example, adding two 2-D numpy arrays corresponds to matrix addition.</span></li>
</ul>

In [7]:
X=np.array([[1, 0], [0, 1]])
Y=np.array([[2, 1], [1, 2]])

Z=X+Y
display(Z)

array([[3, 1],
       [1, 3]])


<h3><img class="aligncenter wp-image-5334" style="display: block; margin-left: auto; margin-right: auto;" src="images/MatrixAddition.png" alt="An example of matrix addition." width="488" height="227" />Difference between NumPy Arrays and Lists</h3>
<ul>
<li>What happens if we take two lists and put a plus sign between them?</li>
<li>Remember, putting a plus sign between two lists&nbsp;concatenates those two lists, resulting in a new list which is longer than&nbsp;the two lists that were added together.</li>
</ul>

In [9]:
x = [1, 0, -1]
y = [0, 1, 2]

display(x+y)

[1, 0, -1, 0, 1, 2]

<ul>
<li>What happens if we first turn those lists into NumPy arrays,&nbsp;and then have a plus sign between them?</li>
<li>In this case, what's happening is we have two one-dimensional arrays.&nbsp;And what we've accomplished here is an element-wise addition&nbsp;between these two arrays.</li>
</ul>

In [10]:
x = np.array([1, 0, -1])
y = np.array([0, 1, 2])

display(x+y)

array([1, 1, 1])


<hr>
<h3>Reference</h3>
<p>Jukka-Pekka Onnela, Python for Research, Python Libraries and Concepts Used in Research, CC 2.2.2_ Slicing NumPy Arrays, edX, <a href="https://www.edx.org/course/using-python-for-research" target="_blank" rel="noopener">https://www.edx.org/course/using-python-for-research</a>&nbsp;</p>