<h1>Indexing Numpy Arrays</h1><p><img src="images/1line.png" width="100%" /></p>
<ul>
<li>NumPy arrays can also be indexed with other arrays or other sequence-like objects like lists.</li>
<li>This can be used to process a large vector or matrix of data very rapidly - with out having to loop though the data with a for loop.</li>
</ul>
<p>For Example:</p>
<ul>
<li>Create a npArray z1.</li>
<li>Create a second array, z2, which is 1 added to every element in z1.</li>
<li>Assume I wan to extract the elements at index 0, 2 and 3
<ul>
<li>I can create a list [0, 2, 3]&nbsp;</li>
<li>then apply the array to the np array z1&nbsp;</li>
<li>this produces a new np array with the elements at index 0, 2, 3 from np array z1</li>
</ul>
</li>
</ul>




In [21]:
# import numpy
import numpy as np

z1 = np.array([1, 3, 4, 5, 7, 9])
z2 = z1 + 1
z2

array([ 2,  4,  5,  6,  8, 10])

In [22]:
ind = [0, 2, 3]
z1[ind]

array([1, 4, 5])

<ul>
<li>In this example, index or ind, was defined as a Python list, but we could also have defined that as a NumPy array.</li>
<li>You take the previous list, 0, 2, 3, turn that into a NumPy array or a (e.g. np.array([0, 2, 3])), and still do the indexing.</li>
<li>In other words, we can index NumPy arrays using either lists or other NumPy arrays.</li>
</ul>
<h2 id="Numpy:-Boolean-Indexing">Boolean Indexing</h2>
<ul>
<li>NumPy arrays can also be indexed using logical indices, but what does that actually mean?</li>
<li>Just as we can have an array of numbers, we&nbsp;can have an array consisting of true and false.</li>
<li>Assuming the same z1 array as above, we can use a boolean expression, like z1 greater than 6, to create a Boolean array.</li>
<li>We then index an array z1 by using a Boolean "mask".&nbsp;It is called <strong>fancy indexing</strong>, if arrays are indexed by using boolean or integer arrays (masks).</li>
<li>In our next example, we will use the Boolean mask of one array (z1) to select the corresponding elements of another array. The new array z3 contains all the elements of z2 where the corresponding value of (z1&gt;6) is True.</li>
</ul>


In [16]:
import numpy as np

z1 = np.array([1, 3, 4, 5, 7, 9])
z1 > 6

array([False, False, False, False,  True,  True])

In [17]:
# Use the Boolean array to extract all values > 6 from z1
z1[z1>6]

array([7, 9])

In [20]:
# Use the same Boolean Array to extract last two values from another array
z2 = z1 + 1
z3 = z2[z1>6]
z3

array([ 8, 10])

<ul>
<li>Every element of the Array z1 is tested, if it is greater than 6. The results of these tests are the Boolean elements of the result array.</li>
<li>Of course, it is also possible to check using any Boolean operator "==", "!=", &lt;", "&lt;=", "&gt;" and "&gt;=".</li>
<li>It works also for higher dimensions:</li>
</ul>


In [15]:
Z = np.array([[42,56,89,65],
              [99,88,42,12],
              [55,42,17,18]])
Z>=42

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [ True,  True, False, False]])

<ul>
<li>It is a convenient way to <em>threshold</em> images.</li>
</ul>


In [14]:
import numpy as np

A = np.array([
[12, 13, 14, 12, 16, 14, 11, 10,  9],
[11, 14, 12, 15, 15, 16, 10, 12, 11],
[10, 12, 12, 15, 14, 16, 10, 12, 12],
[ 9, 11, 16, 15, 14, 16, 15, 12, 10],
[12, 11, 16, 14, 10, 12, 16, 12, 13],
[10, 15, 16, 14, 14, 14, 16, 15, 12],
[13, 17, 14, 10, 14, 11, 14, 15, 10],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 17, 19, 16, 17, 18, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 12, 14, 11, 12, 14, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11]])
B = A < 15
display(B.astype(np.int32))

array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 0, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1]])

<ul>
<li>If you have a close look at the previous output, you will see, that it the upper case 'A' is hidden in the array B.</li>
</ul>
<p>&nbsp;</p>
<h3>Indexing vs. Slicing</h3>
<ul>
<li>One final word about indexing NumPy arrays-- and this&nbsp;is really important because it can easily&nbsp;lead to subtle programming errors.</li>
<li>When you slice an array using the colon operator, you get a <strong>view</strong> of the object. This means that if you modify it, the original array will also be modified.</li>
</ul>

<h4>Slicing (Shallow Copy)</h4>
<p><img style="display: block; margin-left: auto; margin-right: auto;" src="images/shallowSlice.PNG" width="682" height="483" alt="shows memory location fo z2 is the same as for array z1" /></p>
<ul>
<li>In the above images, I'm going to define my z1 to be <br />z1 = np.array([1, 3, 5, 7]).</li>
<li>Then, I will define a new vector "z2" tha is a slice&nbsp;from 0 to 4.</li>
<li>I can look at the contents of my z2.</li>
<li>In this case, I choose to modify the element at location zero.</li>
<li>So I'm just going to type&nbsp;z2[0], is equal to 3.</li>
<li>I can now inspect the content of z2, and instead of having 1, 3, 5 and z,&nbsp;I have 3, 3, 5, and 7, as we would have expected.</li>
<li>However, if I now type z1, you will see that the first element at location is 0 of that array has also been modified.</li>
</ul>



In [11]:
import numpy as np

z1 = np.array([1, 3, 5, 7])
z2 = z1[0:4]  # Z2 is slicesd from z1
display(z2)   # array([1, 3, 5, 7])

z2[0] = 3
display(z2)   # array([3, 3, 5, 7])

display(z1)   # array([3, 3, 5, 7])

array([1, 3, 5, 7])

array([3, 3, 5, 7])

array([3, 3, 5, 7])

<h4>Indexing (Deep Copy)</h4>
<ul>
<li>This is in contrast with what happens when you index an array, in which case&nbsp;what is returned to you is a copy of the original data.</li>
</ul>
<p><img style="display: block; margin-left: auto; margin-right: auto;" src="images/deepIndex.PNG" width="740" height="433" alt="shows memory location fo z2 different to that of z1" /></p>
<ul>
<li>As before, I'm going to define my z1 vector&nbsp;to be <br />z1 = np.array([1, 3, 5, 7]).</li>
<li>Then define the index vector as z1&lt;8.</li>
<li>I now define z2 as all of elements in z1 where z1 &lt; 8.</li>
<li>The contents of z2 is 1, 3, 5 and 7.</li>
<li>So I'm just going to type&nbsp;z2[0], is equal to 3.</li>
<li>I can now inspect the content of z2, and instead of having 1, 3, 5 and 7,&nbsp;I have 3, 3, 5, and 7, as we would have expected.</li>
<li>If I now type z1, you will see that the first element at location is 0 has NOT changed.</li>
</ul>

In [10]:
import numpy as np

z1 = np.array([1, 3, 5, 7])

z2 = z1[z1<8] # z2 based on a filter of z1
display(z2)   # array([1, 3, 5, 7])

z2[0] = 3
display(z2)   # array([3, 3, 5, 7])

display(z1)   # array([1, 3, 5, 7])

array([1, 3, 5, 7])

array([3, 3, 5, 7])

array([1, 3, 5, 7])

<hr />
<h3>Reference</h3>
<p>Jukka-Pekka Onnela, Python for Research, Python Libraries and Concepts Used in Research, CC 2.2.3_ Indexing NumPy Arrays, edX, <a href="https://www.edx.org/course/using-python-for-research" target="_blank" rel="noopener">https://www.edx.org/course/using-python-for-research</a>&nbsp;</p>